# Generated by Django 2.1.5 on 2019-02-05 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='betin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='last_five_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='match_date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='soccerway_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='table_score',
            field=models.IntegerField(default=0),
        ),
    ]
