# Generated by Django 2.1.5 on 2019-02-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190206_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
